### ISSUE TITLE
Standardization Barrier Block "Data Layers"

### ISSUE THREAD

**Issue by NotJeven** [Moesh/Calamity#104]
I definitely think that all of the systems should be relative based on barrier block data layers. I think that these data layers should be x/z coordinate planes starting at the top of the world (y=255) and moving down. This will give as much area as possible to build levels. These should be standardized for level designers to use. They can be stored in structure blocks to load with each level.

Basically if it doesn't make sense to use an entity marker, lets use a data layer.

Layers needed:
* (void to map height moving_piston) Map edge build limit 
* Spawn 1
* Spawn 2
* Iron ore counting area
* In bounds/Out bounds
* Height build limit moving_piston ^ ¹

^ would be nice to have but I do not think it is required
¹ I can solve this problem without this layer, but the solution is magnitudes better with it.

The list continues?

I am game to implement.

**Comment by Moesh** [comment]
Resolved by 2b090cc5025f8038afd79a0605243d6052431484
