### ISSUE TITLE
Out of bounds cheating message plays when players are still technically in bounds

### ISSUE THREAD

**Issue by Moesh** [Moesh/Calamity#135]
A player attempting to leave the play area for the first time should not be punished for curiosity. This isn't like the spawn area.

**Comment by NotJeven** [comment]
I am a fan of a "soft out of bounds" where gamemode = adventure and the messages are shown. With the way arenas are to be encapsulated this could work as long as boats are dealt with. If not throwing a "soft" bounds 1 block around the arena before the "hard" bounds could be cool too.

**Comment by Moesh** [comment]
Early on, I took the decision to have a soft boundary, then void. This should have been what is already happening. This is what the layer at 254 is supposed to represent.

For the team spawn, I opted to kill them immediately because of the implications of gameplay/placing blocks/death looping.

**Comment by Moesh** [comment]
Resolved by 59305226a54a3cded2916d140fb696b14df7c836
