### ISSUE TITLE
Beds do not explode in the overworld, even if the biome is from the nether or end.

### ISSUE THREAD

**Issue by Vilder50** [Moesh/Calamity#17]
I might be wrong, but I'm pretty sure you intended beds to blow up when the player sleeps in them, but they don't.

This makes beds kind of op since the player can change their spawn point.
Also if the bed is broken the player will lose their spawn point resulting in them respawning in the void over and over for the rest of the game.

**Comment by Moesh** [comment]
Could easily resolve this by changing the Bed recipe to produce TNT--that would be pretty funny. 2 TNT per Bed? Those materials would be roughly equivalent...3, if I really wanted to be kind.

**Comment by Vilder50** [comment]
It sounds confusing and none logical if the bed recipe gave TNT. (And I have no idea how you would explain the recipe to the player without it feeling like a super random recipe to them)

The way I see it is to fix it in one of these ways:
* Move the map into the nether or end.
* Try recreating the bed explosion. 
* Change the overworld dimension to make beds explode (Dimension changing is experimental though, so don't think it's a good idea to use yet.)
* Remove the recipe.
* Make it impossible for the player to change spawn point using beds.

**Comment by Moesh** [comment]
I figure if a player wants to make a bed and then is surprised by seeing TNT come up, the issues resolves itself fairly quickly.

I do have a copy of the map in the nether (if you were enterprising, you may have noticed it by now ;)). I would like to move it to the nether.

**Comment by Moesh** [comment]
To be clear, I would banking on the idea of surprise mechanics being enjoyable and intriguing to players.

**Comment by Moesh** [comment]
Can you speak on why dimension changing is buggy? I think once they are in the nether, I should be able to keep them there.

**Comment by Vilder50** [comment]
I meant changing as in changing the overworld dimension using a [datapack](https://minecraft.gamepedia.com/Custom_dimension#Dimension_type) is experimental. I'm pretty sure setting `bed_works` to false would make them blow up in the overworld.

There shouldn't be any problems with teleporting the player to other dimensions.

**Comment by Moesh** [comment]
Everything is stored in structures, so we have the luxury of literally not caring about what the world saves as, or if it gets corrupted. Time for a TOTALLY NEW VISUAL STYLE.
