### ISSUE TITLE
Players should be able to choose their starter weapon

### ISSUE THREAD

**Issue by Moesh** [Moesh/Calamity#19]
**What?**

Players should feel have a weapon or tool (to be used as a weapon in a pinch) that is powerful. We want to give them a choice between the following weapons:
- Iron Shovel
- Iron Axe
- Iron Pickaxe
- Iron Hoe

These items will have the following statistics:
- 10 Durability left
- Curse of Vanishing

**Why?**

This item is intended to be a quick but dirty weapon freshly spawned players can use to defend their base in a pinch. Previous this was the Iron Axe as it had the same damage as a Stone Sword. This is serving two purposes:
- The attacking player must have a plan to handle freshly spawned player coming at them. Are they getting support from their team with Strength or Regeneration?
- The defending team should feel like they have the slight advantage when in their own base. This is resolved by giving them slight speed, regeneration, and other low-level effects for ~7-10 seconds (from memory).
- Players can get right back into an action and gather their chosen resource for their defense or movement throughout the map.

**How?**

With the selection system, I am envisioning the players first spawning with all weapons. The first weapon to use durability will trigger a function which clears any the other items on the player, if they are present.

I am looking for a solution which can be used across multiple layouts and maps, which means no physical block implementation. It would also be sweet if it feels...natural, you know?

**Comment by Vilder50** [comment]
I have been thinking about how to implement the "First weapon to use durability will be kept" thing and I have almost figured out how to make it in a simple way and make it problem free.

The only problem I'm having is that before the player uses any of their items they could take all their starting weapons but the weapon they want to use and put them into a furnace smelting them into iron nuggets. (And thereby get free points). Players could jump into the void over and over and farm iron/points that way.

So either we have to remove the smelting tools recipes, use different none iron tools or look at a different method.

I think we should remove the iron tool smelting recipes. What do you think?

**Comment by Moesh** [comment]
Perhaps we use Stone or Wood tools and alter the stats?

**Comment by Moesh** [comment]
I see, the Smelting Recipes aren't important to the gameplay of Calamity--perhaps we could change it to a trash item instead.
