### ISSUE TITLE
Bossbar should reflect who is winning

### ISSUE THREAD

**Issue by Moesh** [Moesh/Calamity#29]
The bossbar is pretty useful, but I'd like to bring some more visual impact to the map.

- [x] If the score is tied, bossbar does not change color
- [x] If the blue or red in winning, the bossbar changes to that team's color
- [x] Text should be updated to reflect current team's score or winning state. It should look like: 
  - [ ] Tied score! | <N> Ore Left
  - [ ] <Red/Blue> <score>/<N> | <N> Ore Left
  - [ ] <Red/Blue> wins!

**Comment by EpicPuppy613** [comment]
Maybe make a resource pack that goes either way, example attached:
![image](https://user-images.githubusercontent.com/61771471/110385499-d9199b00-8013-11eb-92ee-7fafaf5207e5.png)

**Comment by Moesh** [comment]
> Maybe make a resource pack that goes either way, example attached:
> ![image](https://user-images.githubusercontent.com/61771471/110385499-d9199b00-8013-11eb-92ee-7fafaf5207e5.png)

While cool, I'd like something that feels a bit more oppressive to the players. If a team is behind, they should feel that extra pressure they need to succeed.
